/**
 * diz_eng.js
 * Dizionario monolingue inglese-inglese (livelli A1/A2)
 * Per il test INVALSI Grado 8
 */

// Vocabolario chiave per le prove di listening e reading comprehension
const vocabEnglish = {
  // Verbi comuni
  'be': 'to exist; to have a state or quality',
  'have': 'to own or possess something',
  'do': 'to perform an action',
  'go': 'to move from one place to another',
  'make': 'to create or produce something',
  'come': 'to arrive or approach',
  'see': 'to perceive with your eyes',
  'know': 'to have information or be familiar with',
  'get': 'to receive or obtain',
  'take': 'to grab or carry something',
  'say': 'to speak or tell',
  'think': 'to use your mind to consider',
  'like': 'to enjoy or prefer',
  'want': 'to desire something',
  'give': 'to present or offer',
  'find': 'to discover or locate',
  'tell': 'to communicate information',
  'ask': 'to request information',
  'work': 'to do a job or labor',
  'call': 'to use the telephone or name someone',
  'try': 'to attempt or make an effort',
  'leave': 'to depart from a place',
  'put': 'to place something somewhere',
  'mean': 'to have as significance',
  'keep': 'to retain or maintain',
  'let': 'to allow or permit',
  'begin': 'to start',
  'seem': 'to appear to be',
  'help': 'to assist or aid',
  'play': 'to engage in activity for enjoyment',
  'move': 'to change position',
  'live': 'to reside or dwell',
  'believe': 'to think something is true',
  'hold': 'to carry or grasp',
  'bring': 'to carry towards',
  'happen': 'to occur or take place',
  'write': 'to put words on paper',
  'provide': 'to supply or give',
  'sit': 'to be in a seated position',
  'stand': 'to be on your feet',
  'lose': 'to no longer have something',
  'pay': 'to give money',
  'meet': 'to encounter someone',
  'include': 'to contain as part of a whole',
  'continue': 'to keep going',
  'set': 'to place or position',
  'learn': 'to gain knowledge',
  'change': 'to make different',
  'lead': 'to guide or direct',
  'understand': 'to comprehend',
  'watch': 'to look at carefully',
  'follow': 'to go after',
  'stop': 'to cease movement',
  'create': 'to make something new',
  'speak': 'to communicate verbally',
  'read': 'to look at and understand written words',
  'allow': 'to permit',
  'add': 'to combine together',
  'spend': 'to use money',
  'grow': 'to increase in size',
  'open': 'to make accessible',
  'walk': 'to move on foot',
  'win': 'to be victorious',
  'offer': 'to propose or present',
  'remember': 'to recall from memory',
  'love': 'to have deep affection',
  'consider': 'to think about',
  'appear': 'to seem or come into view',
  'buy': 'to purchase',
  'wait': 'to stay in expectation',
  'serve': 'to work for or provide food',
  'die': 'to cease living',
  'send': 'to cause to go to someone',
  'expect': 'to anticipate',
  'build': 'to construct',
  'stay': 'to remain',
  'fall': 'to drop downward',
  'cut': 'to use a sharp tool to divide',
  'reach': 'to stretch towards and touch',
  'kill': 'to cause death',
  'produce': 'to create or manufacture',
  'decide': 'to make a choice',
  'raise': 'to lift up or increase',
  'break': 'to damage or crack',
  'spend': 'to pass time',
  'agree': 'to have the same opinion',
  'support': 'to hold up or assist',
  'hit': 'to strike',
  'produce': 'to make or create',
  'eat': 'to consume food',
  'cover': 'to place over',
  'catch': 'to grab or capture',
  'draw': 'to make a picture with a pencil',
  'break': 'to separate into pieces',
  'spend': 'to use money or time',
  'pass': 'to go by or succeed in',
  'shoot': 'to fire a weapon',
  'show': 'to display or reveal',
  'hear': 'to perceive sounds',
  'let': 'to allow',
  'talk': 'to speak',
  'turn': 'to rotate or change direction',
  'start': 'to begin',
  'show': 'to demonstrate',
  'hear': 'to listen and perceive',
  'run': 'to move quickly on foot',
  'hot': 'having high temperature',
  'ask': 'to request',
  'need': 'to require',
  'feel': 'to experience emotion or sensation',
  'become': 'to start being',
  'leave': 'to go away',
  'put': 'to place',
  'mean': 'to intend',
  'keep': 'to hold or retain',
  'let': 'to allow or permit',
  'begin': 'to start',
  'seem': 'to appear',

  // Aggettivi comuni
  'good': 'positive or satisfactory',
  'bad': 'negative or poor quality',
  'big': 'of great size',
  'small': 'of little size',
  'new': 'recently made or acquired',
  'old': 'having existed for a long time',
  'good': 'of high quality',
  'bad': 'of poor quality',
  'long': 'of great length',
  'short': 'not long',
  'high': 'at a great height',
  'low': 'at a small height',
  'different': 'not the same',
  'same': 'identical',
  'large': 'of great size',
  'little': 'very small',
  'early': 'before the expected time',
  'late': 'after the expected time',
  'high': 'extending upward',
  'low': 'close to the ground',
  'easy': 'not difficult',
  'hard': 'difficult',
  'fast': 'moving quickly',
  'slow': 'not moving quickly',
  'hot': 'very warm',
  'cold': 'low in temperature',
  'warm': 'moderately hot',
  'cool': 'moderately cold',
  'clean': 'free from dirt',
  'dirty': 'not clean',
  'dry': 'free from moisture',
  'wet': 'covered with water',
  'happy': 'feeling joy',
  'sad': 'feeling sorrow',
  'angry': 'feeling rage',
  'tired': 'lacking energy',
  'sick': 'having illness',
  'well': 'in good health',
  'strong': 'having great power',
  'weak': 'lacking strength',
  'thick': 'of great depth or width',
  'thin': 'of small width',
  'bright': 'giving light',
  'dark': 'having little light',
  'loud': 'producing much sound',
  'quiet': 'making little sound',
  'fresh': 'recently made',
  'stale': 'no longer fresh',
  'full': 'containing as much as possible',
  'empty': 'containing nothing',
  'rich': 'having much money or wealth',
  'poor': 'lacking money',
  'fair': 'just and reasonable',
  'free': 'not under control',
  'busy': 'having much to do',
  'free': 'not busy',
  'ready': 'prepared',
  'true': 'in accordance with fact',
  'false': 'not true',
  'possible': 'able to happen',
  'impossible': 'unable to happen',
  'safe': 'free from danger',
  'dangerous': 'likely to cause harm',
  'beautiful': 'pleasing to look at',
  'ugly': 'not beautiful',
  'normal': 'ordinary or usual',
  'strange': 'unusual or odd',
  'familiar': 'well known',
  'suitable': 'appropriate',
  'permanent': 'lasting indefinitely',
  'temporary': 'lasting for a limited time',
  'perfect': 'absolutely excellent',
  'natural': 'produced by nature',
  'artificial': 'made by humans',
  'rare': 'not common',
  'common': 'occurring often',
  'wild': 'in its natural state',
  'wild': 'uncontrolled',
  'gentle': 'mild or kind',
  'rough': 'not smooth',
  'smooth': 'without lumps or ridges',
  'bitter': 'having sharp taste',
  'sweet': 'having sugary taste',
  'sour': 'having sharp acid taste',
  'salty': 'having salt taste',
  'deep': 'extending far down',
  'shallow': 'not deep',
  'narrow': 'of small width',
  'wide': 'of great width',
  'tight': 'firmly fixed or fitting closely',
  'loose': 'not firmly fixed',
  'bright': 'shining with light',
  'dark': 'having little light',
  'alive': 'having life',
  'dead': 'no longer alive',
  'kind': 'generous and caring',
  'mean': 'unkind and nasty',
  'mature': 'fully developed',
  'immature': 'not fully developed',
  'wise': 'having good judgment',
  'foolish': 'lacking good sense',
  'lucky': 'having good fortune',
  'unlucky': 'having bad fortune',
  'honest': 'truthful',
  'dishonest': 'not truthful',
  'brave': 'showing courage',
  'cowardly': 'lacking courage',
  'polite': 'showing good manners',
  'rude': 'not showing good manners',
  'modest': 'not boastful',
  'proud': 'feeling dignity or self-respect',
  'lazy': 'unwilling to work',
  'hard-working': 'diligent',
  'selfish': 'concerned only with oneself',
  'generous': 'willing to give',
  'gentle': 'kind and not harsh',
  'violent': 'using or characterized by physical force',
  'calm': 'peaceful',
  'anxious': 'worried or nervous',
  'confident': 'having belief in oneself',
  'shy': 'lacking confidence with people',
  'friendly': 'kind and sociable',
  'hostile': 'unfriendly',
  'optimistic': 'hoping for the best',
  'pessimistic': 'expecting the worst',
  'realistic': 'based on facts',
  'romantic': 'concerned with love',

  // Nomi comuni
  'person': 'a human being',
  'man': 'an adult male human',
  'woman': 'an adult female human',
  'boy': 'a young male human',
  'girl': 'a young female human',
  'child': 'a young human',
  'baby': 'a very young child',
  'parent': 'a mother or father',
  'mother': 'a female parent',
  'father': 'a male parent',
  'sister': 'a female sibling',
  'brother': 'a male sibling',
  'friend': 'a person you know and like',
  'teacher': 'a person who teaches',
  'student': 'a person who studies',
  'doctor': 'a person trained in medicine',
  'nurse': 'a person who cares for patients',
  'worker': 'a person who works',
  'house': 'a building for living',
  'home': 'where someone lives',
  'room': 'a space in a building',
  'door': 'an entrance or exit',
  'window': 'an opening in a wall',
  'table': 'a piece of furniture',
  'chair': 'a seat with a back',
  'bed': 'furniture for sleeping',
  'food': 'something eaten for nutrition',
  'water': 'a transparent liquid',
  'bread': 'a baked food',
  'meat': 'the flesh of an animal',
  'fruit': 'the sweet product of a plant',
  'vegetable': 'a plant eaten as food',
  'drink': 'a liquid consumed for refreshment',
  'cup': 'a container for drinking',
  'plate': 'a dish for food',
  'spoon': 'an eating utensil',
  'fork': 'an eating utensil',
  'knife': 'a sharp cutting tool',
  'book': 'a set of written pages',
  'pen': 'a writing instrument',
  'paper': 'a material for writing',
  'bag': 'a container for carrying',
  'box': 'a container with four sides',
  'money': 'a medium of exchange',
  'price': 'the cost of something',
  'work': 'activity for earning money',
  'job': 'regular employment',
  'time': 'the indefinite continued progress',
  'day': 'a 24-hour period',
  'night': 'the period of darkness',
  'morning': 'early part of the day',
  'afternoon': 'middle part of the day',
  'evening': 'late part of the day',
  'week': 'a period of seven days',
  'month': 'a period of about 30 days',
  'year': 'a period of 365 days',
  'hour': 'a period of 60 minutes',
  'minute': 'a period of 60 seconds',
  'second': 'a unit of time',
  'clock': 'an instrument for measuring time',
  'watch': 'a small timepiece',
  'car': 'a vehicle for transport',
  'bus': 'a large vehicle for passengers',
  'train': 'a vehicle on rails',
  'bike': 'a two-wheeled vehicle',
  'bike': 'a vehicle you pedal',
  'street': 'a public road in a town',
  'road': 'a way for travel',
  'city': 'a large town',
  'town': 'an urban area',
  'village': 'a small settlement',
  'country': 'a nation with its own government',
  'world': 'the earth and all its inhabitants',
  'sky': 'the space above the earth',
  'sun': 'the star at the center of our system',
  'moon': 'a celestial body orbiting earth',
  'star': 'a celestial body',
  'rain': 'water falling from clouds',
  'snow': 'frozen precipitation',
  'wind': 'moving air',
  'fire': 'rapid oxidation producing heat',
  'ice': 'frozen water',
  'mountain': 'a high landform',
  'river': 'a large stream of water',
  'sea': 'a large body of salt water',
  'ocean': 'a very large sea',
  'beach': 'an area of sand by water',
  'garden': 'an area for growing plants',
  'tree': 'a large woody plant',
  'flower': 'the reproductive part of a plant',
  'grass': 'green plants with narrow leaves',
  'animal': 'a living creature',
  'dog': 'a common pet animal',
  'cat': 'a small pet animal',
  'bird': 'an animal with feathers and wings',
  'fish': 'an aquatic animal',
  'horse': 'a large animal',
  'cow': 'a large farm animal',
  'pig': 'a farm animal',
  'chicken': 'a farm bird',
  'snake': 'a long reptile',
  'music': 'organized sounds',
  'song': 'a piece of music with words',
  'dance': 'rhythmic movement',
  'game': 'an activity with rules',
  'sport': 'a physical activity',
  'ball': 'a sphere for playing',
  'toy': 'an object for play',
  'school': 'an institution for learning',
  'class': 'a group of students',
  'lesson': 'a period of instruction',
  'test': 'an examination',
  'exam': 'a test of knowledge',
  'grade': 'a mark for performance',
  'language': 'a system of communication',
  'word': 'a unit of speech',
  'sentence': 'a group of words',
  'story': 'a narrative account',
  'poem': 'a piece of verse',
  'movie': 'a motion picture',
  'film': 'a motion picture',
  'picture': 'a visual image',
  'photo': 'a picture taken with a camera',
  'television': 'an electronic device for viewing',
  'radio': 'a device for sound transmission',
  'phone': 'a device for communication',
  'computer': 'an electronic device',
  'internet': 'a global system of networks',
  'email': 'electronic mail',
  'website': 'a location on the internet',
  'war': 'armed conflict',
  'peace': 'freedom from conflict',
  'government': 'system of ruling',
  'law': 'a rule enforced by government',
  'police': 'law enforcement officers',
  'soldier': 'a military personnel',
  'army': 'military force',
  'health': 'physical and mental well-being',
  'illness': 'a state of poor health',
  'hospital': 'a place for medical care',
  'medicine': 'treatment for illness',
  'drug': 'a substance for treating',
  'disease': 'an illness',
  'pain': 'physical suffering',
  'exercise': 'physical activity',
  'sport': 'a competitive activity',
  'gym': 'a place for exercise',
  'shop': 'a store',
  'market': 'a place for buying/selling',
  'supermarket': 'a large self-service store',
  'restaurant': 'a place serving food',
  'hotel': 'a place to stay',
  'airport': 'a place for aircraft',
  'station': 'a place for transport',
  'library': 'a place with books',
  'museum': 'a place with artifacts',
  'theater': 'a place for performances',
  'cinema': 'a place for watching movies',
  'park': 'an area of public land',
  'church': 'a religious building',
  'temple': 'a religious building',
  'art': 'creative expression',
  'music': 'organized sound',
  'science': 'systematic study',
  'math': 'the study of numbers',
  'history': 'study of the past',
  'geography': 'study of places',
  'culture': 'customs and beliefs',
  'tradition': 'a custom passed down',
  'holiday': 'a day of celebration',
  'birthday': 'anniversary of birth',
  'wedding': 'a marriage ceremony',
  'family': 'group of related people',
  'relative': 'a family member',
  'cousin': 'a child of parent\'s sibling',
  'grandparent': 'parent of a parent',
  'grandchild': 'a child of one\'s child',
  'husband': 'a married man',
  'wife': 'a married woman',
  'son': 'a male child',
  'daughter': 'a female child',
  'love': 'a strong affection',
  'hate': 'intense dislike',
  'fear': 'strong anxiety',
  'anger': 'strong displeasure',
  'joy': 'great happiness',
  'sadness': 'state of sorrow',
  'surprise': 'sudden unexpected event',
  'hope': 'feeling of expectation',
  'dream': 'a series of images in sleep',
  'danger': 'risk of harm',
  'safety': 'protection from harm',
  'beauty': 'quality of being attractive',
  'ugly': 'not beautiful',
  'strength': 'capacity for exertion',
  'weakness': 'lack of strength',
  'success': 'achievement of goal',
  'failure': 'lack of success',
  'luck': 'chance happening',
  'truth': 'quality of being true',
  'lie': 'a false statement',
  'promise': 'a commitment to do',
  'secret': 'something not disclosed',
  'mystery': 'something not understood',
  'problem': 'a difficult situation',
  'solution': 'an answer to a problem',
  'mistake': 'an error',
  'accident': 'an unexpected event',
  'event': 'a thing that happens',
  'experience': 'an event undergone',
  'memory': 'recollection of the past',
  'idea': 'a thought or concept',
  'opinion': 'a view or judgment',
  'fact': 'a thing known to be true',
  'reason': 'a cause or explanation',
  'question': 'a request for information',
  'answer': 'a response to a question',
  'advice': 'guidance or recommendation',
  'news': 'recently received information',
  'information': 'knowledge or facts',
  'knowledge': 'understanding of facts',
  'skill': 'ability to do something well',
  'talent': 'natural aptitude',
  'ability': 'power to do something',
  'effort': 'exertion of power',
  'success': 'accomplishment of goal',
  'achievement': 'a successful accomplishment',
  'award': 'a prize for achievement',
  'prize': 'something won',
  'winner': 'one who wins',
  'loser': 'one who loses',
  'team': 'a group working together',
  'leader': 'one who leads',
  'member': 'one belonging to a group',
  'enemy': 'an adversary',
  'ally': 'a friend or partner',
  'stranger': 'a person unknown',
  'stranger': 'someone you don\'t know',
  'neighbor': 'one living nearby',
  'community': 'a group with shared interests',
  'society': 'a community of people',
  'organization': 'an organized group',
  'business': 'a commercial enterprise',
  'company': 'a commercial business',
  'factory': 'a place of manufacture',
  'farm': 'a place for farming',
  'office': 'a place of business',
  'desk': 'a piece of furniture',
  'computer': 'an electronic device',
  'machine': 'a device with moving parts',
  'tool': 'an implement for working',
  'equipment': 'necessary items for work',
  'material': 'a substance of matter',
  'product': 'something produced',
  'quality': 'the standard of excellence',
  'quantity': 'an amount of something',
  'size': 'physical dimensions',
  'weight': 'heaviness of an object',
  'temperature': 'degree of heat',
  'color': 'visual perception of light',
  'shape': 'outer form or outline',
  'pattern': 'a repeated design',
  'style': 'a distinctive manner',
  'fashion': 'the prevailing custom',
  'clothes': 'garments worn on body',
  'shirt': 'a garment worn above waist',
  'pants': 'a garment for legs',
  'dress': 'a garment for women',
  'shoe': 'a covering for foot',
  'coat': 'a garment for upper body',
  'hat': 'a covering for head',
  'bag': 'a container for carrying',
  'wallet': 'a small folding case',
  'jewelry': 'decorative items worn',
  'ring': 'a circular band of metal',
  'necklace': 'an ornament for neck',
  'watch': 'a timepiece',
  'glasses': 'lenses for vision',
  'camera': 'a device for photography',
  'telephone': 'a device for communication',
  'lamp': 'a device for light',
  'electricity': 'energy from electrons',
  'energy': 'power to do work',
  'power': 'capacity to do something',
  'force': 'a push or pull',
  'weight': 'how heavy something is',
  'height': 'distance from bottom to top',
  'width': 'distance across',
  'length': 'distance from end to end',
  'distance': 'space between two things',
  'speed': 'rate of movement',
  'direction': 'a path or bearing',
  'movement': 'the act of moving',
  'motion': 'a change of position',
  'action': 'a thing done',
  'reaction': 'a response to action',
  'sound': 'vibrations heard by ears',
  'noise': 'unwanted sound',
  'voice': 'sound from speaking',
  'cry': 'a loud shout',
  'laugh': 'a sound of joy',
  'smile': 'an expression of pleasure',
  'tear': 'drops from the eye',
  'blood': 'red fluid in the body',
  'bone': 'hard connective tissue',
  'muscle': 'tissue that produces movement',
  'heart': 'the organ pumping blood',
  'brain': 'the organ of thought',
  'eye': 'the organ of sight',
  'ear': 'the organ of hearing',
  'nose': 'the organ of smell',
  'mouth': 'the opening for eating',
  'tongue': 'the organ in the mouth',
  'tooth': 'a hard structure in the mouth',
  'hair': 'thread-like growth',
  'skin': 'the outer covering of body',
  'finger': 'a digit of the hand',
  'toe': 'a digit of the foot',
  'hand': 'the end of an arm',
  'foot': 'the end of a leg',
  'arm': 'a limb of the body',
  'leg': 'a limb for walking',
  'head': 'the upper part of the body',
  'face': 'the front of the head',
  'body': 'the physical structure',
  'back': 'the rear side of body',
  'belly': 'the front of torso',
  'chest': 'the upper front torso',
  'shoulder': 'the area between neck and arm',
  'neck': 'the part connecting head and body',
  'throat': 'the front of the neck',
  'knee': 'the joint of the leg',
  'elbow': 'the joint of the arm',
  'wrist': 'the joint of the hand',
  'ankle': 'the joint of the foot',
  'hair': 'the threadlike growth on skin',
  'beard': 'hair on the face',
  'mustache': 'hair above the lip',
  'eyebrow': 'hair above the eye',
  'eyelash': 'hair on the eyelid',
  'wrinkle': 'a line on the skin',
  'scar': 'a mark from a wound',
  'freckle': 'a small spot on skin',
  'dimple': 'a small indentation',
  'pimple': 'a small pustule on skin',
  'wound': 'an injury to the body',
  'cut': 'a wound made by cutting',
  'bruise': 'a discoloration from impact',
  'burn': 'an injury from fire',
  'cold': 'a mild illness',
  'cough': 'a forceful exhalation',
  'sneeze': 'a sudden exhalation',
  'fever': 'a high body temperature',
  'allergy': 'a reaction to a substance',
  'ache': 'a continuous pain',
  'headache': 'pain in the head',
  'toothache': 'pain in a tooth',
  'stomachache': 'pain in the stomach',
  'backache': 'pain in the back',
  'sore': 'painful to touch',
  'swelling': 'an enlargement',
  'infection': 'a disease caused by microbes',
  'bacteria': 'single-celled organisms',
  'virus': 'a pathogenic agent',
  'fungi': 'organisms like mold',
  'vaccine': 'a substance for immunity',
  'treatment': 'medical care',
  'surgery': 'a medical operation',
  'cure': 'a remedy for disease',
  'symptom': 'a sign of disease',
  'patient': 'one receiving medical care',
  'nurse': 'one caring for patients',
  'doctor': 'a medical professional',
  'dentist': 'one caring for teeth',
  'pharmacist': 'one dispensing medicine',
  'surgeon': 'a doctor performing surgery',
  'therapist': 'one providing therapy',
  'psychologist': 'one studying the mind',
  'counselor': 'one providing guidance',
  'veterinarian': 'one caring for animals',
  'scientist': 'one doing scientific work',
  'biologist': 'one studying life',
  'chemist': 'one studying chemistry',
  'physicist': 'one studying physics',
  'mathematician': 'one studying math',
  'engineer': 'one designing structures',
  'architect': 'one designing buildings',
  'artist': 'one creating art',
  'musician': 'one creating music',
  'dancer': 'one who dances',
  'actor': 'one performing in plays',
  'actress': 'a female actor',
  'singer': 'one who sings',
  'writer': 'one who writes',
  'author': 'one who writes books',
  'poet': 'one who writes poems',
  'journalist': 'one reporting news',
  'photographer': 'one taking photos',
  'filmmaker': 'one making films',
  'director': 'one directing a production',
  'producer': 'one producing content',
  'manager': 'one managing operations',
  'boss': 'one in authority',
  'employee': 'one working for pay',
  'employer': 'one employing others',
  'customer': 'one buying goods',
  'client': 'one using services',
  'buyer': 'one purchasing items',
  'seller': 'one selling items',
  'merchant': 'one trading goods',
  'trader': 'one engaged in trade',
  'farmer': 'one farming land',
  'fisherman': 'one catching fish',
  'hunter': 'one hunting animals',
  'cook': 'one preparing food',
  'chef': 'a skilled cook',
  'baker': 'one baking bread',
  'butcher': 'one selling meat',
  'tailor': 'one making clothes',
  'carpenter': 'one working with wood',
  'plumber': 'one fixing pipes',
  'electrician': 'one working with electricity',
  'mechanic': 'one repairing machines',
  'driver': 'one driving a vehicle',
  'pilot': 'one flying aircraft',
  'sailor': 'one sailing ships',
  'soldier': 'one serving in military',
  'guard': 'one protecting',
  'judge': 'one hearing cases',
  'lawyer': 'one practicing law',
  'politician': 'one in politics',
  'president': 'one leading government',
  'prime minister': 'chief executive',
  'minister': 'one in government',
  'senator': 'a legislative member',
  'representative': 'one representing others',
  'ambassador': 'one representing a country',
  'diplomat': 'one in diplomacy',
  'spy': 'one gathering intelligence',
  'criminal': 'one committing crimes',
  'prisoner': 'one held in prison',
  'police officer': 'one enforcing law',
  'detective': 'one investigating crimes',
  'firefighter': 'one fighting fires',
  'paramedic': 'one providing emergency care',
  'rescue worker': 'one performing rescues',
  'volunteer': 'one working without pay',
  'intern': 'one in training',
  'apprentice': 'one learning a trade',
  'trainee': 'one in training',
  'recruit': 'one newly enlisted',
  'veteran': 'one with experience',
  'retiree': 'one retired from work',
  'pensioner': 'one receiving a pension',
  'homeless person': 'one without housing',
  'refugee': 'one fleeing danger',
  'immigrant': 'one moving to a country',
  'migrant': 'one moving from place to place',
  'native': 'one from a place',
  'citizen': 'a member of a nation',
  'foreigner': 'one from another country',
  'tourist': 'one traveling for pleasure',
  'traveler': 'one traveling',
  'commuter': 'one traveling to work',
  'pedestrian': 'one walking on foot'
};

console.log('Dictionary loaded: English-English (A1/A2 INVALSI)');
